general {
    lock_cmd = zanken-system-lock
    before_sleep_cmd = OMARCHY_LOCK_ONLY=true zanken-system-lock
    after_sleep_cmd = sleep 1 && zanken-system-wake
    inhibit_sleep = 3
}

listener {
    timeout = 300
    on-timeout = zanken-system-lock
    on-resume = zanken-system-wake
}

listener {
    timeout = 600
    on-timeout = zanken-brightness-display off
    on-resume = zanken-brightness-display on
}
