#!/bin/bash

ENTRY=$(find "$HOME/.password-store" -type f -name "*.gpg" \
  | sed "s|$HOME/.password-store/||" \
  | sed 's|\.gpg$||' \
  | wofi --dmenu --prompt "Password")

[ -z "$ENTRY" ] && exit

PASSWORD=$(pass show "$ENTRY" | head -n1)

# Clear field
printf 'fake-key <Ctrl-a>\n' >> "$QUTE_FIFO"
printf 'fake-key <Backspace>\n' >> "$QUTE_FIFO"

# Type password
printf 'fake-key %s\n' "$PASSWORD" >> "$QUTE_FIFO"
