#!/bin/bash

ENTRY=$(find "$HOME/.password-store" -type f -name "*.gpg" \
  | sed "s|$HOME/.password-store/||" \
  | sed 's|\.gpg$||' \
  | wofi --dmenu --prompt "Username")

[ -z "$ENTRY" ] && exit

USERNAME=$(pass show "$ENTRY" | grep -i '^username:' | cut -d ' ' -f2-)

[ -z "$USERNAME" ] && exit

# Clear field
printf 'fake-key <Ctrl-a>\n' >> "$QUTE_FIFO"
printf 'fake-key <Backspace>\n' >> "$QUTE_FIFO"

# Type username
printf 'fake-key %s\n' "$USERNAME" >> "$QUTE_FIFO"
